openapi: 3.0.0
info:
  title: Admin Push API
  version: 1.0.0
  description: 푸시 요청 API
servers:
  - url: http://220.90.208.217:8080
tags:
  - name: Push
    description: Push 보내기
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /push/admin/token:
    post:
      tags:
        - Push
      summary: 토큰으로 관리자 push
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                token:
                  - >-
                    dKz7V3QcRDq9qHyobwki1N:APA91bHbs_ymFN4ZTzCENb5y-SVUYV2Gd7nrnswsPAzXCNgiP19TdAPhLcrVKIxtWZfleMSMTCNsEFbbTDxNvP2ZBfND9BC7EpWexvDVIArUczFVp6WVZYusVY5CZtVteyrlj5FqAI1k
                category: admin
                title: push title
                body: push body
                url: https://ktest.kofia.or.kr/
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: admin push sent
  /push/admin/user:
    post:
      tags:
        - Push
      summary: uuid로 관리자 push
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                userUuid:
                  - >-
                    49872b77-6aa1-4170-9798-606a25101605
                category: admin
                title: push title
                body: push body
                url: https://ktest.kofia.or.kr/
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: admin push sent
  /push/category:
    post:
      tags:
        - Push
      summary: 항목별 push
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                category: notice
                title: test push title
                body: test push body
                url: https://ktest.kofia.or.kr/
      responses:
        '200':
          description: Successful response
  /push/category/user:
    post:
      tags:
        - Push
      summary: 특정 유저에게 항목 push
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                userUuid:
                  - >-
                    49872b77-6aa1-4170-9798-606a25101605
                category: notice
                title: test push title
                body: test push body
                url: https://ktest.kofia.or.kr/
      responses:
        '200':
          description: Successful response